---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cache-restore
  image: public.ecr.aws/prima/drone-tools:1.20.1
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  depends_on:
  - git-clone

- name: check-secrets
  image: public.ecr.aws/prima/drone-tools:1.20.1
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  depends_on:
  - git-clone

- name: check-public-docker-images
  image: public.ecr.aws/prima/drone-tools:1.20.1
  commands:
  - check-public-docker-images
  depends_on:
  - git-clone

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.20.1
  commands:
  - sed -i 's/USER app/USER root/g' ./Dockerfile
  - docker build -t prima/posexional-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  depends_on:
  - cache-restore

- name: elixir-1-9
  image: public.ecr.aws/prima/elixir-official:1.9.2
  commands:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile --all-warnings --warnings-as-errors
  - mix test
  - mix check
  environment:
    MIX_ENV: test
  depends_on:
  - cache-restore

- name: elixir-1-10
  image: public.ecr.aws/prima/elixir:1.10.4-1
  commands:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile --all-warnings --warnings-as-errors
  - mix test
  - mix check
  environment:
    MIX_ENV: test
  depends_on:
  - elixir-1-9

- name: elixir-1-11
  image: public.ecr.aws/prima/elixir:1.11.2-1
  commands:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile --all-warnings --warnings-as-errors
  - mix test
  - mix check
  environment:
    MIX_ENV: test
  depends_on:
  - elixir-1-9
  - elixir-1-10

- name: cache-save
  image: public.ecr.aws/prima/drone-tools:1.20.1
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save _build deps
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  when:
    branch:
    - master
  depends_on:
  - elixir-1-9
  - elixir-1-10
  - elixir-1-11

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint
- name: docker-conf
  host:
    path: /home/ec2-user/.docker

trigger:
  event:
  - push

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: noreply@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  status:
  - failure
  target:
    exclude:
    - qa
    - qa-stack

depends_on:
- default

---
kind: signature
hmac: 1baab5839c0c187fb64e33d0eab730b6b0d2226a110674b9fe64c6643f4c7fde

...
