apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "posexional"
  description: "Posexional is a library to manage positional files in Elixir"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-claims-settlement"
  system: prima.it
